require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/*
    - lib/generators/**/*
    - lib/templates/**/*
    - node_modules/**/*
    - .simplecov
    - tmp/**/*
    - vendor/**/*
    - cypress/**/*
    - spec/support/webmock.rb

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 90
  AllowedPatterns:
    - '^\s*describe\s.+\sdo$'
    - '^\s*it\s.+\sdo$'
    - '^\s*context\s.+\sdo$'

Lint/AmbiguousBlockAssociation:
  AllowedMethods:
    - not_change

Lint/MissingSuper:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Exclude:
    - features/**/*

Style/BlockDelimiters:
  AllowedMethods: []

Naming/AsciiIdentifiers:
  Exclude:
    - features/**/*

Naming/PredicateName:
  AllowedMethods:
    - is_a?
    - has_functionality?

Naming/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

RSpec/NestedGroups:
  Max: 10

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
