version: '3.8'

volumes:
  postgres: {}

services:
  app:
    container_name: app
    build: .
    depends_on:
     - postgres
    networks:
      - app-net
    ports:
      - 3000:3000

  postgres:
    container_name: postgres_soccer
    image: postgres:13.4-alpine
    environment:
      # POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
    networks:
      - app-net
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    healthcheck:
      test: redis-cli -h 127.0.0.1 ping | grep -q '^PONG$$'
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 6379:6379
    networks:
      - app-net
    volumes:
      - redis:/data

networks:
  app-net: {}
