version: '3.8'

services:
  app:
    environment:
      - RAILS_ENV=test
      - DATABASE_URL=postgresql://postgres_user:postgres_pass@postgres:5432/real-time-score

  linters-app:
    build:
        context: .

  postgres:
    environment:
      DATABASE_NAME: real-time-score_test
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
