version: '3.8'

volumes:
  postgres: {}

networks:
  app-net: {}

services:
  app:
    build:
      context: .
    depends_on:
     - postgres
    networks:
      - app-net
    ports:
      - 3000:3000

  postgres:
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    networks:
      - app-net
    volumes:
      - postgres:/var/lib/postgresql/data
